org: dinalj

app: eilish

service: eilish-bass

package:
  patterns:
    - "!**"
    - "app/**"

provider:
  name: aws
  runtime: python3.13
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.regions.${self:provider.stage}}

functions:
  hello:
    handler: app.handler.hello
    layers:
      - Ref: PythonRequirementsLambdaLayer

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer: true
  regions:
    dev: ap-south-1
