org: dinalj

app: eilish

service: eilish-bass

package:
  patterns:
    - "!**"
    - "app/**"
    - "!**/__pycache__/**"

provider:
  name: aws
  runtime: python3.13
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.regions.${self:provider.stage}}
  websocketsApiName: ${self:service}-${sls:stage}-websockets
  websocketsApiRouteSelectionExpression: $request.body.action
  environment:
    WEBSOCKET_CONNECTIONS_TABLE: !Ref websocketConnectionsTable
    WEBSOCKET_API_ENDPOINT: !Sub "https://${WebsocketsApi}.execute-api.${AWS::Region}.amazonaws.com/${sls:stage}"
  logRetentionInDays: 1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Query
          Resource:
            - !GetAtt websocketConnectionsTable.Arn
            - !Sub "${websocketConnectionsTable.Arn}/index/*"
        - Effect: Allow
          Action:
            - execute-api:ManageConnections
          Resource:
            - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebsocketsApi}/*/*"

functions:
  coreHandlerLambda:
    handler: app.functions.core.handler.lambda_handler
    name: ${self:service}-${sls:stage}-core-handler
    layers:
      - Ref: PythonRequirementsLambdaLayer

  websocketConnectionHandlerLambda:
    handler: app.functions.websocket.connection.handler.lambda_handler
    name: ${self:service}-${sls:stage}-websocket-connection-handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
    layers:
      - Ref: PythonRequirementsLambdaLayer

  websocketDefaultHandlerLambda:
    handler: app.functions.websocket.handler.lambda_handler
    name: ${self:service}-${sls:stage}-websocket-default-handler
    events:
      - websocket:
          route: $default
          routeResponseSelectionExpression: "$default"
    layers:
      - Ref: PythonRequirementsLambdaLayer

  websocketDispatchHandlerLambda:
    handler: app.functions.websocket.dispatch.handler.lambda_handler
    name: ${self:service}-${sls:stage}-dispatch-handler
    events:
      - websocket:
          route: dispatch
    layers:
      - Ref: PythonRequirementsLambdaLayer

resources:
  Resources:
    websocketConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${sls:stage}-websocket-connections
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer: true
  regions:
    dev: ap-south-1
